### ISSUE TITLE
Update the file structure in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-welcome#218]
Current File Structure in CONTRIBUTING.md
![image](https://user-images.githubusercontent.com/78433013/149615561-d8b719c8-5317-4b0b-ae5f-30019d88f65d.png)

Update this to the current file structure we have in repository

**Comment by akash2819** [comment]
Please assign me

**Comment by oneonone97** [comment]
Can you assign me this?
Thank You

**Comment by SidharajYadav** [comment]
Respect Sir,
I'm Siddharaj Yadav a computer engineering undergraduate, Pursuing TE at D Y Patil College under (Pune University).
I am new to open source contribution but I am well aware of Python,Django,HTML and Git& GitHub. I would to contribute to your organization but could you please tell me how to get started? Gsoc
Hoping to hear from you soon
Regards
Siddharaj Yadav
mail- sidharajyadav157@gmail.com

**Comment by NaincyKumariKnoldus** [comment]
Hey @rohan09-raj Can I do this please?

**Comment by rohan09-raj** [comment]
> Hey @rohan09-raj Can I do this please?

Uh oh! sorry already assigned to someone else.
![image](https://user-images.githubusercontent.com/78433013/149619034-d96a049b-9f1e-4ce5-9114-90c96afea978.png)
You can always check the assignee's section before commenting.

**Comment by NaincyKumariKnoldus** [comment]
okay no problem.

**Comment by SidharajYadav** [comment]
Yes BroI try for gsoc Whats why commentSent from Mail for Windows From: Rohan Raj GuptaSent: Saturday, January 15, 2022 4:20 PMTo: Real-Dev-Squad/website-welcomeCc: SidharajYadav; CommentSubject: Re: [Real-Dev-Squad/website-welcome] Update the file structure in `CONTRIBUTING.md` (Issue #218) Hey @rohan09-raj Can I do this please?Uh oh! sorry already assigned to someone else.You can always check the assignee's section before commenting.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by rohan09-raj** [comment]
> Respect Sir, I'm Siddharaj Yadav a computer engineering undergraduate, Pursuing TE at D Y Patil College under (Pune University). I am new to open source contribution but I am well aware of Python,Django,HTML and Git& GitHub. I would to contribute to your organization but could you please tell me how to get started? Gsoc Hoping to hear from you soon Regards Siddharaj Yadav mail- [sidharajyadav157@gmail.com](mailto:sidharajyadav157@gmail.com)

You can join our discord server where we do this feature building stuff on various frameworks and tech.
Read us about more here
https://www.realdevsquad.com/

Discord Server Link
https://www.realdevsquad.com/> Respect Sir, I'm Siddharaj Yadav a computer engineering undergraduate, Pursuing TE at D Y Patil College under (Pune University). I am new to open source contribution but I am well aware of Python,Django,HTML and Git& GitHub. I would to contribute to your organization but could you please tell me how to get started? Gsoc Hoping to hear from you soon Regards Siddharaj Yadav mail- [sidharajyadav157@gmail.com](mailto:sidharajyadav157@gmail.com)

You can join our discord server where we do this feature building stuff on various frameworks and tech.
Read us about more here
https://www.realdevsquad.com/

Discord Server Link
https://discord.gg/XrgzZbbF

**Comment by SidharajYadav** [comment]
Yes , continue Sent from Mail for Windows From: NaincyKumariKnoldusSent: Saturday, January 15, 2022 3:50 PMTo: Real-Dev-Squad/website-welcomeCc: SidharajYadav; CommentSubject: Re: [Real-Dev-Squad/website-welcome] Update the file structure in `CONTRIBUTING.md` (Issue #218) Hey @rohan09-raj Can I do this please?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by SidharajYadav** [comment]
yes , thank you
