### ISSUE TITLE
Same design of the Navigation bar for all the pages of the welcome site.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#87]
Every page on welcome site has a different design of navbar. 

![image](https://user-images.githubusercontent.com/66248039/109116350-63394800-7766-11eb-9df8-577a630c3df0.png)

![image](https://user-images.githubusercontent.com/66248039/109116418-7c41f900-7766-11eb-991b-78bdf41c86fa.png)

![image](https://user-images.githubusercontent.com/66248039/109116436-86fc8e00-7766-11eb-8fa7-6af55cf19517.png)

![image](https://user-images.githubusercontent.com/66248039/109116453-91b72300-7766-11eb-8deb-273e859ace68.png)

It will be better to have even design for all navbars.

**Comment by TD-17** [comment]
I will work on this !

**Comment by Rucha1499** [comment]
Sure!

**Comment by swarajpure** [comment]
@TD-17 We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've got always something for everyone! ⚡ 

Invitation link: https://discord.gg/Av496njw

**Comment by swarajpure** [comment]
@TD-17 We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've got always something for everyone! ⚡ 

Invitation link: https://discord.gg/FyQ8Z5Zm

**Comment by swarajpure** [comment]
@TD-17 We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've always got something for everyone! ⚡ 

Invitation link: https://discord.gg/FyQ8Z5Zm

**Comment by TD-17** [comment]
Thank you !

**Comment by ashwindevx** [comment]
@Rucha1499 Done! 

I'm pretty new to contributing so excuse me for any PR mistakes. Actually, this was my first contribution.

My branch name is `my-branch`

Thank you

**Comment by swarajpure** [comment]
> 
> 
> @Rucha1499 Done!
> 
> I'm pretty new to contributing so excuse me for any PR mistakes. Actually, this was my first contribution.
> 
> My branch name is `my-branch`
> 
> Thank you

Hey @ashwindevx 
Congratulations on your first contribution! 🎉 

As we are open source, all the issues are visible to whole of the world. Since there are so many people, GitHub provides an official way to assign issues and this particular issue was already assigned to @TD-17

Also, you haven't made any PR in the first place. But I went to your profile and checked for the code change. That's a lot of effort! Thank you for that!

Even if there was a PR, we couldn't actually merge it, since the issue was already formally assigned to someone else.

Please be careful with it that you work only on the issues which are not assigned to anyone. But hey! No need to be saddened! You would have learnt at least something by this issue 😄  

You can have a look at other issues in the same repo which are not assigned to anyone. 
Also, you can check other repos of our organisation: https://github.com/Real-Dev-Squad 

Thank you!
Have a great day! 🎉

**Comment by TD-17** [comment]
@Rucha1499  It is completed! I have created a PR

**Comment by ashwindevx** [comment]
@swarajpure Totally understand what you said. Thank you for the help. I'm pretty new to Open Source that's why I made these mistakes. But learned a lot and will take your advice for upcoming contributions. Thank you🙏🏻👍🏻

**Comment by swarajpure** [comment]
> 
> 
> @swarajpure Totally understand what you said. Thank you for the help. I'm pretty new to Open Source that's why I made these mistakes. But learned a lot and will take your advice for upcoming contributions. Thank you🙏🏻👍🏻

Thank you for taking it positively. Highly appreciate it! 🙂 

We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've always got something for everyone! ⚡ 

Invitation link: https://discord.gg/CENAS28V

Copied the message from above with new invite link. Please join 🚀

**Comment by ashwindevx** [comment]
Thank you! Appreciate it! Joined mate! 

Can you assign me this issue https://github.com/Real-Dev-Squad/website-welcome/issues/88?

**Comment by swarajpure** [comment]
> 
> 
> @swarajpure Thank you! Appreciate it! Joined mate!
> 
> Can you assign me this issue #88?

Sorry but this issue is closed now. I guess you've got another issue to work on 😉 
Also, please message on the discord server whenever you wish to work on a particular issue as most of us don't check GitHub notifications (there are a lot of them 😅)
